# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/mongodb_data:/data/db
      - ./mongodb/data/configdb:/data/configdb
      - ./mongodb/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - mongo-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      TZ: Asia/Tokyo
    depends_on:
      - mongo
    networks:
      - mongo-net

networks:
  mongo-net: